# STM32 BOARD SERIAL CONNECTION
SERIAL_PORT = "/dev/ttyACM0"  # stm32
BAUD_RATE = 115200

# API DETAILS
API_IP = "192.168.10.14"  # IP address of laptop
API_PORT = 5000
URL = f"http://{API_IP}:{API_PORT}"
API_TIMEOUT = 90

# ROBOT SETTINGS
OUTDOOR_BIG_TURN = False

#MODIFICATIONS WITHOUT STM CONNECTIONS
USE_STM = True
